apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-app
      app: frontend
    
  template:
    metadata:
      name: result-app
      labels:
        name: result-app
        app: frontend
    spec:
      containers:
        - name: resultsApp
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80   
    
