apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-app
      app: frontend
    
  template:
    metadata:
      name: voting-app
      labels:
        name: voting-app
        app: frontend
    spec:
      containers:
        - name: voting-app
          image: kodekloud/examplevotingapp_vote:v1
          ports:
            - containerPort: 80   
    
